### ISSUE TITLE
undefined method `chomp'

### ISSUE THREAD

**Issue by usure** [joshforisha/chopin#10]
gem versiion: **1.8.23**
ruby version: **ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]**

the error when I run `chopin` by itself, without any parameters:

```
/var/lib/gems/1.9.1/gems/chopin-0.0.9/bin/chopin:7:in `<top (required)>': undefined method `chomp' for nil:NilClass (NoMethodError)
    from /usr/local/bin/chopin:23:in `load'
    from /usr/local/bin/chopin:23:in `<main>'

```

**Comment by joshforisha** [comment]
This was due to not being supplied the required two arguments source and destination. I added a usage message to avoid this.
